//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.28 at 02:06:36 AM CET 
//


package com.insa.swim.orchestrator.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.insa.pdl.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.insa.pdl.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Scenario.Producers }
     * 
     */
    public Scenario.Producers createScenarioProducers() {
        return new Scenario.Producers();
    }

    /**
     * Create an instance of {@link Scenario.Consumers }
     * 
     */
    public Scenario.Consumers createScenarioConsumers() {
        return new Scenario.Consumers();
    }

    /**
     * Create an instance of {@link Scenario.Consumers.Consumer }
     * 
     */
    public Scenario.Consumers.Consumer createScenarioConsumersConsumer() {
        return new Scenario.Consumers.Consumer();
    }

    /**
     * Create an instance of {@link Scenario.Consumers.Consumer.Requests }
     * 
     */
    public Scenario.Consumers.Consumer.Requests createScenarioConsumersConsumerRequests() {
        return new Scenario.Consumers.Consumer.Requests();
    }

    /**
     * Create an instance of {@link Scenario.Information }
     * 
     */
    public Scenario.Information createScenarioInformation() {
        return new Scenario.Information();
    }

    /**
     * Create an instance of {@link Scenario.Producers.Producer }
     * 
     */
    public Scenario.Producers.Producer createScenarioProducersProducer() {
        return new Scenario.Producers.Producer();
    }

    /**
     * Create an instance of {@link Scenario.Consumers.Consumer.Requests.Request }
     * 
     */
    public Scenario.Consumers.Consumer.Requests.Request createScenarioConsumersConsumerRequestsRequest() {
        return new Scenario.Consumers.Consumer.Requests.Request();
    }

    /**
     * Create an instance of {@link Scenario.Information.Esb }
     * 
     */
    public Scenario.Information.Esb createScenarioInformationEsb() {
        return new Scenario.Information.Esb();
    }

}
