//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.28 at 02:06:36 AM CET 
//


package com.insa.swim.orchestrator.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="information">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *                   &lt;element name="esb">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="consumers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="consumer" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="requests">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="providerId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="sendingTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="periodic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                                                 &lt;element name="numberRequests" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="producers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="producer" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="processingTime" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "information",
    "consumers",
    "producers"
})
@XmlRootElement(name = "scenario")
public class Scenario {

    @XmlElement(required = true)
    protected Scenario.Information information;
    @XmlElement(required = true)
    public Scenario.Consumers consumers;
    @XmlElement(required = true)
    public Scenario.Producers producers;

    /**
     * Gets the value of the information property.
     * 
     * @return
     *     possible object is
     *     {@link Scenario.Information }
     *     
     */
    public Scenario.Information getInformation() {
        return information;
    }

    /**
     * Sets the value of the information property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scenario.Information }
     *     
     */
    public void setInformation(Scenario.Information value) {
        this.information = value;
    }

    /**
     * Gets the value of the consumers property.
     * 
     * @return
     *     possible object is
     *     {@link Scenario.Consumers }
     *     
     */
    public Scenario.Consumers getConsumers() {
        return consumers;
    }

    /**
     * Sets the value of the consumers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scenario.Consumers }
     *     
     */
    public void setConsumers(Scenario.Consumers value) {
        this.consumers = value;
    }

    /**
     * Gets the value of the producers property.
     * 
     * @return
     *     possible object is
     *     {@link Scenario.Producers }
     *     
     */
    public Scenario.Producers getProducers() {
        return producers;
    }

    /**
     * Sets the value of the producers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scenario.Producers }
     *     
     */
    public void setProducers(Scenario.Producers value) {
        this.producers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="consumer" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="requests">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="providerId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                       &lt;element name="sendingTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                       &lt;element name="periodic" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                                       &lt;element name="numberRequests" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "consumer"
    })
    public static class Consumers {

        protected List<Scenario.Consumers.Consumer> consumer;

        /**
         * Gets the value of the consumer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the consumer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConsumer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Scenario.Consumers.Consumer }
         * 
         * 
         */
        public List<Scenario.Consumers.Consumer> getConsumer() {
            if (consumer == null) {
                consumer = new ArrayList<Scenario.Consumers.Consumer>();
            }
            return this.consumer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="requests">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="providerId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                             &lt;element name="sendingTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                             &lt;element name="periodic" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *                             &lt;element name="numberRequests" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "id",
            "requests"
        })
        public static class Consumer {

            @XmlElement(required = true)
            protected String name;
            protected byte id;
            @XmlElement(required = true)
            public Scenario.Consumers.Consumer.Requests requests;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the requests property.
             * 
             * @return
             *     possible object is
             *     {@link Scenario.Consumers.Consumer.Requests }
             *     
             */
            public Scenario.Consumers.Consumer.Requests getRequests() {
                return requests;
            }

            /**
             * Sets the value of the requests property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scenario.Consumers.Consumer.Requests }
             *     
             */
            public void setRequests(Scenario.Consumers.Consumer.Requests value) {
                this.requests = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="request" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="providerId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                   &lt;element name="sendingTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                   &lt;element name="periodic" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
             *                   &lt;element name="numberRequests" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "request"
            })
            public static class Requests {

                protected List<Scenario.Consumers.Consumer.Requests.Request> request;

                /**
                 * Gets the value of the request property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the request property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRequest().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Scenario.Consumers.Consumer.Requests.Request }
                 * 
                 * 
                 */
                public List<Scenario.Consumers.Consumer.Requests.Request> getRequest() {
                    if (request == null) {
                        request = new ArrayList<Scenario.Consumers.Consumer.Requests.Request>();
                    }
                    return this.request;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="providerId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *         &lt;element name="sendingTime" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *         &lt;element name="periodic" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
                 *         &lt;element name="numberRequests" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "providerId",
                    "size",
                    "sendingTime",
                    "periodic",
                    "period",
                    "numberRequests"
                })
                public static class Request {

                    protected byte providerId;
                    protected short size;
                    protected short sendingTime;
                    @XmlElement(required = true)
                    protected String periodic;
                    protected Short period;
                    protected Byte numberRequests;

                    /**
                     * Gets the value of the providerId property.
                     * 
                     */
                    public byte getProviderId() {
                        return providerId;
                    }

                    /**
                     * Sets the value of the providerId property.
                     * 
                     */
                    public void setProviderId(byte value) {
                        this.providerId = value;
                    }

                    /**
                     * Gets the value of the size property.
                     * 
                     */
                    public short getSize() {
                        return size;
                    }

                    /**
                     * Sets the value of the size property.
                     * 
                     */
                    public void setSize(short value) {
                        this.size = value;
                    }

                    /**
                     * Gets the value of the sendingTime property.
                     * 
                     */
                    public short getSendingTime() {
                        return sendingTime;
                    }

                    /**
                     * Sets the value of the sendingTime property.
                     * 
                     */
                    public void setSendingTime(short value) {
                        this.sendingTime = value;
                    }

                    /**
                     * Gets the value of the periodic property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPeriodic() {
                        return periodic;
                    }

                    /**
                     * Sets the value of the periodic property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPeriodic(String value) {
                        this.periodic = value;
                    }

                    /**
                     * Gets the value of the period property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Short }
                     *     
                     */
                    public Short getPeriod() {
                        return period;
                    }

                    /**
                     * Sets the value of the period property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Short }
                     *     
                     */
                    public void setPeriod(Short value) {
                        this.period = value;
                    }

                    /**
                     * Gets the value of the numberRequests property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getNumberRequests() {
                        return numberRequests;
                    }

                    /**
                     * Sets the value of the numberRequests property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setNumberRequests(Byte value) {
                        this.numberRequests = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}duration"/>
     *         &lt;element name="esb">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "id",
        "duration",
        "esb",
        "date"
    })
    public static class Information {

        @XmlElement(required = true)
        protected String name;
        protected byte id;
        @XmlElement(required = true)
        protected Duration duration;
        @XmlElement(required = true)
        protected Scenario.Information.Esb esb;
        @XmlElement(required = true)
        protected String date;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(byte value) {
            this.id = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setDuration(Duration value) {
            this.duration = value;
        }

        /**
         * Gets the value of the esb property.
         * 
         * @return
         *     possible object is
         *     {@link Scenario.Information.Esb }
         *     
         */
        public Scenario.Information.Esb getEsb() {
            return esb;
        }

        /**
         * Sets the value of the esb property.
         * 
         * @param value
         *     allowed object is
         *     {@link Scenario.Information.Esb }
         *     
         */
        public void setEsb(Scenario.Information.Esb value) {
            this.esb = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "version"
        })
        public static class Esb {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String version;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVersion(String value) {
                this.version = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="producer" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="processingTime" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "producer"
    })
    public static class Producers {

        protected List<Scenario.Producers.Producer> producer;

        /**
         * Gets the value of the producer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the producer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProducer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Scenario.Producers.Producer }
         * 
         * 
         */
        public List<Scenario.Producers.Producer> getProducer() {
            if (producer == null) {
                producer = new ArrayList<Scenario.Producers.Producer>();
            }
            return this.producer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="processingTime" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "id",
            "processingTime"
        })
        public static class Producer {

            @XmlElement(required = true)
            protected String name;
            protected byte id;
            protected byte processingTime;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public byte getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the processingTime property.
             * 
             */
            public byte getProcessingTime() {
                return processingTime;
            }

            /**
             * Sets the value of the processingTime property.
             * 
             */
            public void setProcessingTime(byte value) {
                this.processingTime = value;
            }

        }

    }

}
